### PR TITLE
remove default values for date and datetime fields

### PR DESCRIPTION
**Pull request by erral**
Otherwise you get some strange exception when starting the instance:

```
zope.configuration.xmlconfig.ZopeXMLConfigurationError: File "/var/csmant/instances/XXXX.buildout/parts/instance/etc/site.zcml", line 16.2-16.23
    ZopeXMLConfigurationError: File "/var/csmant/downloads/eggs/Products.CMFPlone-4.3.4.1-py2.7.egg/Products/CMFPlone/configure.zcml", line 98.4-102.10
    ZopeXMLConfigurationError: File "/var/csmant/instances/XXX.buildout/src/XXX.XXX/XXX/XXX/configure.zcml", line 17.4-17.39
    ZopeXMLConfigurationError: File "/var/csmant/instances/XXX.buildout/src/XXX.XXX/XXX/XXX/configure.zcml", line 26.4-26.29
    WrongType: ('', <type 'datetime.datetime'>, '')
 
```

### CODE REVIEW

**Comment by ale-rt** [comment]
The proper default might be None or a defaultFactory can be suggested: https://plone-training.readthedocs.io/en/master/mastering-plone/dexterity_3.html

**Comment by MrTango** [comment]
@erral could you add something like this too:
`# defaultFactory=${7:get_default_${1}},",`
I did that already for Choice Field. ;).

**Comment by erral** [comment]
Done and rebased.

**Comment by MrTango** [comment]
thx

**Pull request merged**
